export const RUS_STRINGS = {
  contactsTitle: 'Контакты:',
  contactsLocation: 'г. Санкт-Петербург',
  hardSkillsGer: 'Немецкий язык – C1 (продвинутый)',
  hardSkillsEng: 'Английский язык – B1 (средний)',
  hardSkillsRus: 'Русский язык – C2 (родной)',
  softSkillsEngineer: 'Инженер',
  softSkillsMathematician: 'Математик',
  softSkillsAnalyst: 'Аналитик',
  softSkillsAssiduity: 'Усидчивость',
  softSkillsTeamwork: 'Командность',
  softSkillsPlanning: 'Планирование',
  myName: 'Асауляк Никита',
  aboutTitle: 'Обо мне:',
  aboutInner:
    'Я аналитически мыслю и всегда стремлюсь находить логическое решение поставленным задачам. Люблю учиться новому и преодолевать трудности, не придумывая их на пустом месте. Неконфликтный и коммуникабельный. Из хобби могу выделить футбол и большой теннис. Также люблю велопрогулки, природу и компьютерные игры.',
  workExperienceTitle: 'Опыт работы:',
  workFirstName: 'Junior Frontend Developer',
  workFirstPlace: 'Aston, Санкт-Петербург',
  workFirstTime: 'февраль 2024 - апрель 2024',
  workSecName: 'Су-Шеф',
  workSecPlace: 'Агастиар, Санкт-Петербург',
  workSecTime: 'март 2021 – февраль 2022',
  workThirdName: 'Инженер-проектировщик',
  workThirdPlace: 'Вильдау, Германия',
  workThirdTime: 'май 2021 – сентябрь 2021',
  educationTitle: 'Образование:',
  educationFirstName: 'Бакалавр Инженер',
  educationFirstPlace: 'Вильдау, Германия',
  educationSecName: 'Бакалавр Менеджер',
  educationSecPlace: 'СПбПУ, Санкт-Петербург',
  coursesTitle: 'Курсы:',
  coursesFirstTime: 'декабрь 2021 – март 2022',
  coursesSecTime: 'сентябрь 2022 – январь 2022',
  coursesThirdTime: 'сентябрь 2022 – декабрь 2022',
  coursesFourthTime: 'декабрь 2023 - февраль 2024',
  projectsTitle: 'Проекты:',
  projectsSubtitle: 'Для перехода нажмите на название',
  lastUpdate: 'Последнее обновление: апрель 2024',
};


export const GER_STRINGS = {
  contactsTitle: 'Kontakte zur Kommunikation:',
  contactsLocation: 'Sankt Petersburg',
  hardSkillsGer: 'Deutsche Sprache – C1 (verhandlungssichere Sprachkenntnisse)',
  hardSkillsEng: 'Englische Sprache – B1 (gute Sprachkenntnisse)',
  hardSkillsRus: 'Russische Sprache – C2 (Muttersprache)',
  softSkillsEngineer: 'Ingenieur',
  softSkillsMathematician: 'Mathematiker',
  softSkillsAnalyst: 'Analytiker',
  softSkillsAssiduity: 'Ausdauer',
  softSkillsTeamwork: 'Zusammenarbeit',
  softSkillsPlanning: 'Planung',
  myName: 'Asauliak Nikita',
  aboutTitle: 'Über mich:',
  aboutInner:
    'Ich habe analytischen Verstand und gebe mein Bestes, um die gestellten Aufgaben logisch zu lösen. Ich mag neue Dinge lernen und Schwierigkeiten überwinden, ohne sie aus dem Nichts zu erfinden. Ich bin konfliktfrei und kontaktfreudig. Zu meinen Hobbys gehören Fußball und Tennis. Außerdem mag ich Radfahren, die Natur und Computerspiele.',
  workExperienceTitle: 'Berufserfahrung:',
  workFirstName: 'Trainee-Junior Frontend Developer',
  workFirstPlace: 'Aston, Sankt Petersburg',
  workFirstTime: 'Februar 2024 - April 2024',
  workSecName: 'Sous-Chef',
  workSecPlace: 'Agastiar, Sankt Petersburg',
  workSecTime: 'März 2021 – Februar 2022',
  workThirdName: 'Konstrukteur (Entwicklungsingenieur)',
  workThirdPlace: 'Wildau, Deutschland',
  workThirdTime: 'Mai 2021 – September 2021',
  educationTitle: 'Studium:',
  educationFirstName: 'Bachelor im Ingenieurwesen',
  educationFirstPlace: 'TH Wildau, Deutschland',
  educationSecName: 'Bachelor in Geschäftsführung',
  educationSecPlace:
    'St. Petersburger Polytechnische Universität Peter des Großen',
  coursesTitle: 'Kurse:',
  coursesFirstTime: 'Dezember 2021 – März 2022',
  coursesSecTime: 'September 2022 – Januar 2022',
  coursesThirdTime: 'September 2022 – Dezember 2022',
  coursesFourthTime: 'Dezember 2023 - Februar 2024',
  projectsTitle: 'Projekte:',
  projectsSubtitle: 'Für Einzelheiten klicken Sie auf den Titel',
  lastUpdate: 'Aktualisiert im April 2024',
}; 

export const ENG_STRINGS = {
  contactsTitle: 'Contacts:',
  contactsLocation: 'Saint Petersburg',
  hardSkillsGer: `German – C1 (business fluent skills)`,
  hardSkillsEng: 'English – B1 (good skills)',
  hardSkillsRus: 'Russian – C2 (native language)',
  softSkillsEngineer: 'Engineer',
  softSkillsMathematician: 'Mathematician',
  softSkillsAnalyst: 'Analyst',
  softSkillsAssiduity: 'Assiduity',
  softSkillsTeamwork: 'Teamwork',
  softSkillsPlanning: 'Planning',
  myName: 'Asauliak Nikita',
  aboutTitle: 'About me:',
  aboutInner:
    "I have a clear, logical mind and always strive to find a solution to assigned tasks. I love learning new things and overcoming difficulties without making them up out of nowhere. I'm non-conflict and sociable. My hobbies include football and tennis. I also love cycling, nature and computer games.",
  workExperienceTitle: 'Work experience:',
  workFirstName: 'Trainee-Junior Frontend Developer',
  workFirstPlace: 'Aston, St. Petersburg',
  workFirstTime: 'february 2024 - april 2024',
  workSecName: 'Sous Chef',
  workSecPlace: 'Agastiar, St. Petersburg',
  workSecTime: 'march 2021 – february 2022',
  workThirdName: 'Constructor (Development engineer)',
  workThirdPlace: 'Wildau, Germany',
  workThirdTime: 'may 2021 – september 2021',
  educationTitle: 'Studies:',
  educationFirstName: 'Bachelor of Engineering',
  educationFirstPlace: 'TH Wildau, Germany',
  educationSecName: 'Bachelors in Business Management',
  educationSecPlace: 'St. Petersburg Polytechnic University of Peter the Great',
  coursesTitle: 'Courses:',
  coursesFirstTime: 'december 2021 – march 2022',
  coursesSecTime: 'september 2022 – january 2022',
  coursesThirdTime: 'september 2022 – december 2022',
  coursesFourthTime: 'december 2023 - february 2024',
  projectsTitle: 'Projects:',
  projectsSubtitle: 'Click on the title for details',
  lastUpdate: 'Last update: april 2024',
};